# Generated by Django 5.2.11 on 2026-02-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_alter_order_payment_method_alter_order_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('cake', 'Cake'), ('muffins', 'Muffins'), ('croissant', 'Croissant'), ('bread', 'Bread'), ('tart', 'Tart'), ('favorite', 'Favorite')], default='favorite', max_length=20)),
                ('short_desc', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('prep_time', models.PositiveIntegerField(default=10)),
                ('cook_time', models.PositiveIntegerField(default=15)),
                ('servings', models.PositiveIntegerField(default=2)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
